# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration_duty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='student', max_length=20)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_me', models.TextField(blank=True, default='', max_length=1000)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.DepartmentInfo')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds_designation', to='user_app.Designation')),
                ('sanctioning_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctioning_auth', to='user_app.Designation')),
                ('sanctioning_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctioning_officer', to='user_app.Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='administration',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.Designation'),
        ),
    ]
