# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_duty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='student', max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('relationship_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.DepartmentInfo')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='sanctioning_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctioning_leave_to', to='user_app.Designation'),
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='sanctioning_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Designation'),
        ),
        migrations.AddField(
            model_name='administration',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Designation'),
        ),
    ]
