# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
