# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration_duty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administration',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.Designation'),
        ),
    ]
