# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20170828_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
