# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20170830_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='unique_id',
            field=models.IntegerField(default=1),
        ),
    ]
