# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_extrainfo_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='unique_id',
            field=models.IntegerField(unique=True),
        ),
    ]
