# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20170830_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='relationship_status',
        ),
    ]
