# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentleaverequest',
            name='permission',
            field=models.CharField(default='academic', max_length=20),
        ),
    ]
