# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavescount',
            name='commuted',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type_of_leave',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('restricted', 'Restricted Holidays'), ('vacation', 'Vacation Leave'), ('commuted', 'Commuted Leave'), ('earned', 'Earned Leave'), ('special_casual', 'Special Casual Leave')], default='casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavescount',
            name='special_casual',
            field=models.IntegerField(default=15),
        ),
    ]
