# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0002_leavemigration_migrationchangedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemigration',
            name='rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.Replacement'),
        ),
    ]
