# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0002_auto_20170831_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currentleaverequest',
            name='permission',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
