# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0003_auto_20170827_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='both',
        ),
    ]
