# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0003_auto_20170910_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemigration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
