# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0004_remove_leaverequest_both'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
