# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0006_auto_20170829_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentleaverequest',
            name='station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='station',
            field=models.BooleanField(default=False),
        ),
    ]
