# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('type_of_event', models.CharField(choices=[('working', 'Working Day'), ('holiday', 'Holiday'), ('restricted', 'Restricted Holiday')], max_length=20)),
            ],
        ),
    ]
